#CONFIGS

export BLUETEC_PROCESSOR_KAFKA_SERVER=10.142.0.11:9092,10.142.0.19:9092,10.142.0.46:9092
export BLUETEC_PROCESSOR_KAFKA_GROUPID=telemetry-enrichment-processor
export BLUETEC_PROCESSOR_KAFKA_NUMCONSUMERS=3
export BLUETEC_PROCESSOR_KAFKA_POLL=1000
export BT_PROC_ENRICHMENT_KAFKA_GROUPID=telemetry-enrichment-processor
export BT_PROC_ENRICHMENT_KAFKA_TOPIC_DESTINATION=bt.msg.telemetry.transformation
export BT_PROC_ENRICHMENT_KAFKA_TOPIC_SOURCE=bt.msg.telemetry.enrichment
export BT_PROC_ENRICHMENT_KAFKA_TOPIC_ERROR=bt.msg.telemetry.enrichment.error
export BT_PROC_ENRICHMENT_KAFKA_SERVERS=10.142.0.11:9092,10.142.0.19:9092,10.142.0.46:9092
export BT_PROC_ENRICHMENT_KAFKA_NUMCONSUMERS=3
export BT_PROC_ENRICHMENT_KAFKA_POLL=1000
export BT_PROC_ENRICHMENT_MYSQL_HOST=172.16.101.67
export BT_PROC_ENRICHMENT_MYSQL_PORT=3306
export BT_PROC_ENRICHMENT_MYSQL_DATABASE=bluetec
export BT_PROC_ENRICHMENT_MYSQL_USER=bluetec_web
export BT_PROC_ENRICHMENT_MYSQL_PASSWORD=BL$T#Cw3b
export BT_PROC_ENRICHMENT_SERVER_PORT=8084
export SPRING_DATASOURCE_URL=jdbc:mysql://172.16.101.67:3306/bluetec
export SPRING_DATASOURCE_USERNAME=bluetec_web
export SPRING_DATASOURCE_PASSWORD=BL$T#Cw3b