version: "2"

services:

  telemetry-enrichment-processor:
    image: bluetec/telemetry-enrichment-processor:latest
    container_name: "telemetry-enrichment-processor"
    restart: always
    ports:
      - 8084:8080

    extra_hosts:
      - "ip-172-32-66-85:172.32.66.85"

    volumes:
      - /code:/tmp/code

    environment:
      BLUETEC_PROCESSOR_KAFKA_SERVER: "ip-172-32-66-85:9092"
      BLUETEC_PROCESSOR_KAFKA_GROUPID: "telemetry-enrichment-processor"
      BLUETEC_PROCESSOR_KAFKA_NUMCONSUMERS: "3"
      BLUETEC_PROCESSOR_KAFKA_POLL: "1000"      
      
      BT_PROC_ENRICHMENT_KAFKA_GROUPID: "telemetry-enrichment-processor"
      BT_PROC_ENRICHMENT_KAFKA_TOPIC_DESTINATION: "bt.msg.telemetry.transform"
      BT_PROC_ENRICHMENT_KAFKA_TOPIC_SOURCE: "bt.msg.telemetry.enrichment"
      BT_PROC_ENRICHMENT_KAFKA_TOPIC_ERROR: "bt.msg.telemetry.enrichment.error"
      BT_PROC_ENRICHMENT_KAFKA_SERVERS: "ip-172-32-66-85:9092"
      BT_PROC_ENRICHMENT_KAFKA_NUMCONSUMERS: "3"
      BT_PROC_ENRICHMENT_KAFKA_POLL: "1000"


      BT_PROC_ENRICHMENT_MYSQL_HOST: "ip-172-32-66-85"
      BT_PROC_ENRICHMENT_MYSQL_PORT: 3306
      BT_PROC_ENRICHMENT_MYSQL_DATABASE: "bluetec"
      BT_PROC_ENRICHMENT_MYSQL_USER: "root"
      BT_PROC_ENRICHMENT_MYSQL_PASSWORD: "root"
      BT_PROC_ENRICHMENT_SERVER_PORT: "8080"

      SPRING_DATASOURCE_URL: "jdbc:mysql://ip-172-32-66-85:3306/bluetec"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
